--- #YAML:1.0
name:               Regexp-Grammars
version:            1.034
abstract:           Add grammatical parsing features to Perl 5.10 regexes
author:
    - Damian Conway <DCONWAY@CPAN.org>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Test::More:  0
    version:     0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.57_05
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
