--- #YAML:1.0
name:                Regexp-Grammars
version:             1.005
abstract:            Add grammatical parsing features to Perl 5.10 regexes
license:             ~
author:              
    - Damian Conway <DCONWAY@CPAN.org>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Test::More:                    0
    version:                       0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
